### ISSUE TITLE
Property '_ref' does not exist on type 'FirebaseListObservable<any>'

### ISSUE THREAD

**Issue by NilsHolger** [Soolan/the-sherlock-project#2]
need a fix for this

**Comment by NilsHolger** [comment]
workaround
in index.html get reference to firebase database directly:
  <script src="https://www.gstatic.com/firebasejs/3.7.1/firebase.js"></script>
<script>
  // Initialize Firebase
  // TODO: Replace with your project's customized code snippet
  var config = {
    apiKey: "",
    authDomain: "",
    databaseURL: "",
    storageBucket: "",
    messagingSenderId: ""
  };
  firebase.initializeApp(config);
</script>
       let records = this.corpus._ref.once('value');
      can be replaced with:
      let ref = firebase.database().ref("Evidence/Corpus/Articles");
      let records = ref.once("value");

**Comment by Soolan** [comment]
Hi Nils,
I fail to reproduce the issue. Would you confirm that you are using the
same libs/versions as this repo?

**Comment by NilsHolger** [comment]
using newest angular cli and npm install.

**Comment by Soolan** [comment]
Thanks Nils,
Upgrading the code with the latest libs, requires a couple of updates in several places. I will take care of it later next month and will let you know.
